name: "Notify Discord"

on:
  release:
    types: [ released ]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send notification
        uses: nhevia/discord-styled-releases@v1.2.3
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
