name: "Notify Discord"

on:
  release:
    types: [ released ]

jobs:
  run_main:
    runs-on: ubuntu-18.04
    name: Send release notification to Discord
    steps:
      - name: Send notification
        uses: nhevia/discord-styled-releases@v1.2.3
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
